// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hazatvlxpkfcpuagaism.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhemF0dmx4cGtmY3B1YWdhaXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MjA1MTEsImV4cCI6MjA2NDA5NjUxMX0.X4ofgTePg7spG16fpPtB8FCM6csbog9vwZstIwJD8Io";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);